version: '3.3'

services:

  authelia:
    image: authelia/authelia
    networks:
      services-net:
        aliases:
          - authelia
    volumes:
      - /shared/authelia:/config
    healthcheck:
      disable: true
    environment:
      - TZ=France/Paris
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - "bunkerized-nginx.SERVER_NAME=auth.example.com"
        - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
        - "bunkerized-nginx.REVERSE_PROXY_URL=/"
        - "bunkerized-nginx.REVERSE_PROXY_HOST=http://authelia:9091"

  redis:
    image: redis:alpine
    networks:
      services-net:
        aliases:
          - redis
    volumes:
      - /shared/redis:/data
    environment:
      - TZ=France/Paris

  myapp1:
    image: php:fpm
    networks:
      services-net:
        aliases:
          - myapp1
    volumes:
      - /shared/www/app1.example.com:/app
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - "bunkerized-nginx.SERVER_NAME=app1.example.com"
        - "bunkerized-nginx.USE_AUTHELIA=yes"
        - "bunkerized-nginx.AUTHELIA_BACKEND=https://auth.example.com"
        - "bunkerized-nginx.AUTHELIA_UPSTREAM=http://authelia:9091"
        - "bunkerized-nginx.REMOTE_PHP=myapp1"
        - "bunkerized-nginx.REMOTE_PHP_PATH=/app"

  myapp2:
    image: php:apache
    networks:
      services-net:
        aliases:
          - myapp2
    volumes:
      - /shared/www/app2.example.com:/var/www/html
    deploy:
      placement:
        constraints:
          - "node.role==worker"
      labels:
        - "bunkerized-nginx.SERVER_NAME=app2.example.com"
        - "bunkerized-nginx.USE_AUTHELIA=yes"
        - "bunkerized-nginx.AUTHELIA_BACKEND=https://auth.example.com"
        - "bunkerized-nginx.AUTHELIA_UPSTREAM=http://authelia:9091"
        - "bunkerized-nginx.USE_REVERSE_PROXY=yes"
        - "bunkerized-nginx.REVERSE_PROXY_URL=/"
        - "bunkerized-nginx.REVERSE_PROXY_HOST=http://myapp2"

networks:
  services-net:
    external:
      name: services-net
