version: '3.8'

services:

  redis:
    image: redis:alpine
    networks:
      - config-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==worker"

networks:
  config-net:
    external:
      name: config-net
