version: '3'

services:

  mywww:
    image: bunkerity/bunkerized-nginx
    restart: always
    depends_on:
      - myphp
    ports:
      - 80:8080
      - 443:8443
    # bunkerized-nginx runs as an unprivileged user with UID/GID 101
    # don't forget to edit the permissions of the files and folders accordingly
    volumes:
      - ./web-files:/www:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./bunkerized-nginx-clamav:/plugins/clamav # you will need to download the plugin see download-plugin.sh
    environment:
      - SERVER_NAME=www.example.com # replace with your domain
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - REMOTE_PHP=myphp
      - REMOTE_PHP_PATH=/app

  clamav-server:
    image: mkodockx/docker-clamav:alpine-idb-amd64

  clamav-rest-api:
    image: benzino77/clamav-rest-api
    depends_on:
      - clamav-server
    environment:
      - NODE_ENV=production
      - CLAMD_IP=clamav-server
      - APP_PORT=8080
      - APP_FORM_KEY=FILES

  myphp:
    image: php:fpm
    restart: always
    volumes:
      - ./web-files:/app
